import type { InsertPresetWordList } from "@shared/schema";

export const presetWordLists: InsertPresetWordList[] = [
  {
    name: "Alphabet Letters",
    category: "alphabet",
    description: "All 26 letters of the alphabet",
    words: ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"],
    gradeLevel: "Preschool",
    sortOrder: 1,
  },
  {
    name: "Short Vowel Sounds",
    category: "phonics",
    description: "Words with short vowel sounds (a, e, i, o, u)",
    words: ["cat", "hat", "bat", "mat", "sat", "bed", "red", "pet", "wet", "hen", "pig", "big", "dig", "sit", "hit", "hot", "pot", "dog", "log", "fog", "cup", "bug", "hug", "run", "sun"],
    gradeLevel: "Kindergarten",
    sortOrder: 2,
  },
  {
    name: "Long Vowel Sounds",
    category: "phonics",
    description: "Words with long vowel sounds",
    words: ["cake", "make", "take", "lake", "bake", "bee", "see", "tree", "free", "green", "bike", "like", "kite", "time", "fine", "bone", "home", "note", "rope", "hope", "cube", "tube", "cute", "mule", "rule"],
    gradeLevel: "Kindergarten",
    sortOrder: 3,
  },
  {
    name: "CVC Words",
    category: "cvc",
    description: "Consonant-Vowel-Consonant words for beginning readers",
    words: ["cat", "bat", "hat", "mat", "sat", "rat", "can", "fan", "man", "pan", "ran", "van", "bed", "fed", "led", "red", "wed", "beg", "leg", "peg", "big", "dig", "fig", "pig", "wig", "bit", "fit", "hit", "kit", "lit", "sit", "wit", "bob", "cob", "job", "mob", "rob", "sob", "cot", "dot", "got", "hot", "lot", "not", "pot", "bug", "dug", "hug", "jug", "mug", "rug", "tug", "bun", "fun", "gun", "nun", "run", "sun"],
    gradeLevel: "Kindergarten",
    sortOrder: 4,
  },
  {
    name: "Dolch Sight Words - Pre-K",
    category: "sight_words",
    description: "Pre-Kindergarten Dolch sight words",
    words: ["a", "and", "away", "big", "blue", "can", "come", "down", "find", "for", "funny", "go", "help", "here", "I", "in", "is", "it", "jump", "little", "look", "make", "me", "my", "not", "one", "play", "red", "run", "said", "see", "the", "three", "to", "two", "up", "we", "where", "yellow", "you"],
    gradeLevel: "Preschool",
    sortOrder: 5,
  },
  {
    name: "Dolch Sight Words - Kindergarten",
    category: "sight_words",
    description: "Kindergarten Dolch sight words",
    words: ["all", "am", "are", "at", "ate", "be", "black", "brown", "but", "came", "did", "do", "eat", "four", "get", "good", "have", "he", "into", "like", "must", "new", "no", "now", "on", "our", "out", "please", "pretty", "ran", "ride", "saw", "say", "she", "so", "soon", "that", "there", "they", "this", "too", "under", "want", "was", "well", "went", "what", "white", "who", "will", "with", "yes"],
    gradeLevel: "Kindergarten",
    sortOrder: 6,
  },
  {
    name: "Dolch Sight Words - 1st Grade",
    category: "sight_words",
    description: "First grade Dolch sight words",
    words: ["after", "again", "an", "any", "ask", "as", "by", "could", "every", "fly", "from", "give", "going", "had", "has", "her", "him", "his", "how", "just", "know", "let", "live", "may", "of", "old", "once", "open", "over", "put", "round", "some", "stop", "take", "thank", "them", "then", "think", "walk", "were", "when"],
    gradeLevel: "1st Grade",
    sortOrder: 7,
  },
  {
    name: "Dolch Sight Words - 2nd Grade",
    category: "sight_words",
    description: "Second grade Dolch sight words",
    words: ["always", "around", "because", "been", "before", "best", "both", "buy", "call", "cold", "does", "don't", "fast", "first", "five", "found", "gave", "goes", "green", "its", "made", "many", "off", "or", "pull", "read", "right", "sing", "sit", "sleep", "tell", "their", "these", "those", "upon", "us", "use", "very", "wash", "which", "why", "wish", "work", "would", "write", "your"],
    gradeLevel: "2nd Grade",
    sortOrder: 8,
  },
  {
    name: "Dolch Sight Words - 3rd Grade",
    category: "sight_words",
    description: "Third grade Dolch sight words",
    words: ["about", "better", "bring", "carry", "clean", "cut", "done", "draw", "drink", "eight", "fall", "far", "full", "got", "grow", "hold", "hot", "hurt", "if", "keep", "kind", "laugh", "light", "long", "much", "myself", "never", "only", "own", "pick", "seven", "shall", "show", "six", "small", "start", "ten", "today", "together", "try", "warm"],
    gradeLevel: "3rd Grade",
    sortOrder: 9,
  },
  {
    name: "Blends - Beginning",
    category: "phonics",
    description: "Words starting with consonant blends (bl, br, cl, cr, etc.)",
    words: ["black", "blue", "block", "blend", "brag", "bring", "brown", "brush", "clap", "clean", "climb", "clock", "crab", "cream", "crisp", "crop", "drop", "drum", "drink", "drive", "flag", "flip", "float", "floor", "frog", "from", "front", "fruit", "glad", "glass", "globe", "glue", "grab", "grape", "grass", "green", "grill", "group", "grow"],
    gradeLevel: "1st Grade",
    sortOrder: 10,
  },
  {
    name: "Digraphs",
    category: "phonics",
    description: "Words with digraphs (ch, sh, th, wh, ph)",
    words: ["chat", "cheese", "chest", "chick", "child", "chin", "chip", "chop", "church", "shade", "shake", "shape", "share", "sheep", "shell", "ship", "shirt", "shoe", "shop", "short", "shot", "show", "shut", "thank", "that", "the", "them", "then", "there", "these", "they", "thick", "thin", "thing", "think", "this", "those", "three", "whale", "what", "wheat", "wheel", "when", "where", "which", "while", "white", "who", "why", "phone", "photo"],
    gradeLevel: "1st Grade",
    sortOrder: 11,
  },
  {
    name: "Numbers as Words",
    category: "sight_words",
    description: "Number words from zero to twenty",
    words: ["zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten", "eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen", "seventeen", "eighteen", "nineteen", "twenty"],
    gradeLevel: "Kindergarten",
    sortOrder: 12,
  },
  {
    name: "Color Words",
    category: "sight_words",
    description: "Common color words",
    words: ["red", "orange", "yellow", "green", "blue", "purple", "pink", "brown", "black", "white", "gray", "gold", "silver"],
    gradeLevel: "Preschool",
    sortOrder: 13,
  },
  {
    name: "Days and Months",
    category: "sight_words",
    description: "Days of the week and months of the year",
    words: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
    gradeLevel: "1st Grade",
    sortOrder: 14,
  },
];
